# Generated by Django 4.1.7 on 2023-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRental',
            fields=[
                ('RENT_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('VID_NUM', models.CharField(max_length=300, null=True)),
                ('DETAIL_FEE', models.CharField(max_length=300, null=True)),
                ('DETAIL_DUEDATE', models.DateTimeField(null=True)),
                ('DETAIL_RETURNDATE', models.DateTimeField(null=True)),
                ('DETAIL_DAILYLATEFEE', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('MEM_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('MEM_FNAME', models.CharField(max_length=300, null=True)),
                ('MEM_LNAME', models.CharField(max_length=300, null=True)),
                ('MEM_STREET', models.CharField(max_length=300, null=True)),
                ('MEM_CITY', models.CharField(max_length=300, null=True)),
                ('MEM_STATE', models.CharField(max_length=300, null=True)),
                ('MEM_ZIP', models.CharField(max_length=300, null=True)),
                ('MEM_BALANCE', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MOVIE_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('MOVIE_TITLE', models.CharField(max_length=300, null=True)),
                ('MOVIE_YEAR', models.CharField(max_length=300, null=True)),
                ('MOVIE_COST', models.CharField(max_length=300, null=True)),
                ('MOVIE_GENRE', models.CharField(max_length=300, null=True)),
                ('PRICE_CODE', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('PRICE_CODE', models.IntegerField(primary_key=True, serialize=False)),
                ('PRICE_DESCRIPTION', models.CharField(max_length=300, null=True)),
                ('PRICE_RENTFEE', models.CharField(max_length=300, null=True)),
                ('PRICE_DAILYLATEFEE', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('RENT_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('RENT_DATE', models.DateTimeField(null=True)),
                ('MEM_NUM', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('VID_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('VID_INDATE', models.IntegerField(null=True)),
                ('MOVIE_NUM', models.IntegerField(null=True)),
            ],
        ),
    ]
