# Generated by Django 4.1.5 on 2023-03-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0005_alter_rental_mem_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='MOVIE_NUM',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='VIDEO',
        ),
        migrations.RemoveField(
            model_name='video',
            name='MOVIE',
        ),
        migrations.AddField(
            model_name='movie',
            name='VID_NUM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.video'),
        ),
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='MOVIE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.movie'),
        ),
    ]
